[build]
  functions = "netlify/functions"

[functions]
  # 设置函数运行的地区（建议选离目标服务器近的，但 Netlify 免费版通常默认 us-east-1）
  # node_bundler = "esbuild" 
  # 设置超时时间（Netlify 免费版限制 10s，如果任务长可能会超时，Pro 版可达 26s）
  external_node_modules = ["@sparticuz/chromium"]

